// Emit public/version.js (gitignored, regenerated on install) so the editor can
// show its own version and check GitHub for a newer release. Single-sources the
// version from package.json; the repo slug is where releases of the IDE + host
// script are published (build.yml attaches the host .mjs to v* releases).
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const app = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(readFileSync(path.join(app, "package.json"), "utf8"));
const REPO = "obus-globus/lb-scripting";

const out = `// generated by scripts/gen-version.mjs — do not edit\nwindow.__IDE__ = ${JSON.stringify({ version, repo: REPO })};\n`;
writeFileSync(path.join(app, "public", "version.js"), out);
console.log(`wrote public/version.js (v${version})`);
