#!/usr/bin/env bash
# Produces dist/nf-inject-bundled-<VERSION>.js — a single self-contained script
# that embeds both jars (base64) and self-extracts them on load, so a user only
# has to drop ONE file in their scripts/ folder (it relocates itself into
# scripts/lib/). Also emits a versioned copy of the plain library,
# dist/nf-inject-<VERSION>.js.
#
# NOTE: the bundle only helps the *runtime-attach* path (JDK runtime, e.g.
# GraalVM): on load it writes the jars into scripts/lib/nf-inject-<VERSION>/ and
# points Inject.agentJar there, then attaches when you first inject. The
# -javaagent path is unaffected (that flag needs the jar on disk at JVM launch,
# before any script runs), so -javaagent users still ship the jars themselves.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; cd "$here"

AGENT="dist/nf-inject-agent.jar"; HOLDER="dist/nf-holder.jar"
[ -f "$AGENT" ] && [ -f "$HOLDER" ] || { echo "FAIL: run ./build.sh first ($AGENT / $HOLDER missing)" >&2; exit 1; }

# Single source of truth for the version: the VERSION constant in nf-inject.js.
VERSION="$(grep -oP 'const VERSION = "\K[^"]+' nf-inject.js)"
[ -n "$VERSION" ] || { echo "FAIL: could not read VERSION from nf-inject.js" >&2; exit 1; }

AGENT_B64="$(base64 -w0 "$AGENT")"
HOLDER_B64="$(base64 -w0 "$HOLDER")"
OUT="dist/nf-inject-bundled-${VERSION}.js"
PLAIN="dist/nf-inject-${VERSION}.js"

# Compile the tiny NfToast message-box helper and embed its bytecode (base64) in
# the generated JS — it is NOT shipped inside the jars. nf-inject.js writes it to
# disk at runtime and launches it as a separate process (its own AWT event thread
# -> the dialog reliably shows, unlike an in-process modal from the render thread).
JAVAC="${JAVA_HOME:-/usr/lib/jvm/java-21-openjdk-amd64}/bin/javac"
rm -rf build/toast && mkdir -p build/toast
"$JAVAC" --release 21 -d build/toast src/NfToast.java
TOAST_B64="$(base64 -w0 build/toast/NfToast.class)"
TOAST_LINE="globalThis.__NF_TOAST_CLASS_B64 = \"${TOAST_B64}\";"

# Versioned copy of the plain library (for users who ship the jars themselves),
# with the embedded NfToast bytecode prepended.
{ echo "$TOAST_LINE"; cat nf-inject.js; } > "$PLAIN"

# Ship a versioned copy of the type definitions next to the script, so TS
# consumers get types from a release without copying nf-inject.d.ts by hand.
# The plain and bundled builds share the same API, so one .d.ts covers both.
DTS="dist/nf-inject-${VERSION}.d.ts"
cp nf-inject.d.ts "$DTS"

{
  cat <<'PROLOGUE'
// nf-inject-bundled — GENERATED by make-bundle.sh. Do not edit by hand.
//
// Single-file build of lb-inject: the agent + holder jars are embedded below as
// base64 and self-extracted on load. Drop just THIS file in your scripts/ folder
// (it relocates itself into scripts/lib/) and `load()` it from your own script;
// it defines globalThis.Inject like nf-inject.js.
//
//   load("<scripts>/lib/nf-inject-bundled-<VERSION>.js");
//   var h = Inject.inject("net.minecraft.client.Minecraft","getFps","HEAD", fn);
//
// Self-extraction enables the runtime-attach path (JDK runtime). For the
// -javaagent path you still need the jar on disk at JVM launch (see README).

globalThis.__NF_IS_BUNDLE = true;

(function () {
    var System_ = Java.type("java.lang.System");
    var Files = Java.type("java.nio.file.Files");
    var Paths = Java.type("java.nio.file.Paths");
    var Base64 = Java.type("java.util.Base64");
PROLOGUE

  printf '    %s\n' "$TOAST_LINE"
  printf '    var VERSION = "%s";\n' "$VERSION"
  printf '    var AGENT_B64 = "%s";\n' "$AGENT_B64"
  printf '    var HOLDER_B64 = "%s";\n' "$HOLDER_B64"

  cat <<'EXTRACT'
    try {
        // Resolve the LiquidBounce scripts/lib/nf-inject-<VERSION>/ folder.
        var root;
        try { root = "" + Client.configSystem.rootFolder.getAbsolutePath(); }
        catch (e) { root = "" + System_.getProperty("user.dir"); }
        var dir = Paths.get(root, "scripts", "lib", "nf-inject-" + VERSION);
        Files.createDirectories(dir);
        var agentJar = dir.resolve("nf-inject-agent.jar");
        var holderJar = dir.resolve("nf-holder.jar");   // name fixed: agent's Boot-Class-Path resolves it next to itself
        var agentBytes = Base64.getDecoder().decode(AGENT_B64);
        var holderBytes = Base64.getDecoder().decode(HOLDER_B64);
        // Skip rewriting if already present with matching size (faster reloads).
        if (!Files.exists(agentJar) || Files.size(agentJar) !== agentBytes.length) Files.write(agentJar, agentBytes);
        if (!Files.exists(holderJar) || Files.size(holderJar) !== holderBytes.length) Files.write(holderJar, holderBytes);
        globalThis.__NF_BUNDLED_AGENT_JAR = "" + agentJar.toAbsolutePath();
    } catch (e) {
        throw new Error("nf-inject-bundled: could not extract embedded jars: " + e);
    }
})();

EXTRACT

  # the library itself, verbatim
  cat nf-inject.js

  cat <<'EPILOGUE'

// Point the freshly-defined Inject at the self-extracted agent jar.
(function () {
    if (typeof globalThis.Inject !== "undefined" && globalThis.__NF_BUNDLED_AGENT_JAR) {
        globalThis.Inject.agentJar = globalThis.__NF_BUNDLED_AGENT_JAR;
    }
})();
EPILOGUE
} > "$OUT"

echo "built $OUT ($(du -h "$OUT" | cut -f1)) + $PLAIN + $DTS  [VERSION $VERSION; agent $(du -h "$AGENT"|cut -f1) + holder $(du -h "$HOLDER"|cut -f1) embedded]"
